on:
  push:
    branches:
      - main

name: Build Docker images

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DOCKER_ORG: makerdao
      VDB_BUILDER_NAME: vdb-builder
      VDB_RUNNER_NAME: vdb-runner

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.15'
    - run: go run github.com/onsi/ginkgo/ginkgo -r

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract commit hash
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        SHA_TAG: ${{ steps.vars.outputs.sha_short }}
        LATEST_TAG: latest
      run: |
        # Build Docker images and
        # push them to Docker repo
        docker build -f dockerfiles/$VDB_BUILDER_NAME/Dockerfile \
                     -t $DOCKER_ORG/$VDB_BUILDER_NAME:$SHA_TAG \
                     -t $DOCKER_ORG/$VDB_BUILDER_NAME:$LATEST_TAG \
                     .
        docker build -f dockerfiles/$VDB_RUNNER_NAME/Dockerfile \
                     -t $DOCKER_ORG/$VDB_RUNNER_NAME:$SHA_TAG \
                     -t $DOCKER_ORG/$VDB_RUNNER_NAME:$LATEST_TAG \
                     .
        docker push $DOCKER_ORG/$VDB_BUILDER_NAME --all-tags
        docker push $DOCKER_ORG/$VDB_RUNNER_NAME --all-tags
